apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
data:
  SPRING_PROFILES_ACTIVE: local
  PORT: "7010"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_ID: log-service
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI: http://log-service:7020
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_PREDICATES_0: "Path=/api/logs/**"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_ID: event-consumer
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_URI: http://event-consumer:7030
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_PREDICATES_0: "Path=/event-consumer/**"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_FILTERS_0: "StripPrefix=1"
  REDIS_HOST: host.docker.internal
  REDIS_PORT: "16379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-service-config
data:
  SPRING_PROFILES_ACTIVE: local
  PORT: "7020"
  DB_HOST: host.docker.internal
  DB_PORT: "15432"
  DB_NAME: log-analyzer-db
  KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:29092
  KAFKA_TOPIC_LOG_EVENTS: log-analyzer.dev.log-events
  OPENSEARCH_URL: http://host.docker.internal:19200
  OPENSEARCH_READ_TARGET: log-analyzer-dev-logs-read
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-consumer-config
data:
  SPRING_PROFILES_ACTIVE: local
  PORT: "7030"
  DB_HOST: host.docker.internal
  DB_PORT: "15432"
  DB_NAME: log-analyzer-db
  KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:29092
  KAFKA_CONSUMER_GROUP_ID: event-consumer-k8s
  KAFKA_CONSUMER_RETRY_MAX_ATTEMPTS: "3"
  KAFKA_CONSUMER_RETRY_INTERVAL_MS: "1000"
  KAFKA_TOPIC_LOG_EVENTS: log-analyzer.dev.log-events
  KAFKA_TOPIC_LOG_EVENTS_DLQ: log-analyzer.dev.log-events-dlq
  OPENSEARCH_URL: http://host.docker.internal:19200
  OPENSEARCH_INDEX_NAME: log-analyzer-dev-logs-write
  OPENSEARCH_PIPELINE_NAME: log-analyzer-dev-logs-pipeline
