apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: log-analyzer-local

resources:
  - namespace.yaml
  - configmaps.yaml
  - gateway-service.yaml
  - log-service.yaml
  - event-consumer.yaml
