-- Log Analyzer local PostgreSQL initialization script
-- PostgreSQL 15+

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- =========================================================
-- Users / Auth
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           varchar(255) NOT NULL UNIQUE,
    password_hash   varchar(255) NOT NULL,
    display_name    varchar(100) NOT NULL,
    status          varchar(30) NOT NULL DEFAULT 'ACTIVE',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_users_status
    CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'DELETED'))
    );

CREATE TABLE IF NOT EXISTS user_roles (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL,
    role        varchar(50) NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_user_roles_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT uq_user_roles_user_role
    UNIQUE (user_id, role),

    CONSTRAINT chk_user_roles_role
    CHECK (role IN ('ROLE_ADMIN', 'ROLE_USER'))
    );

-- =========================================================
-- Project / Service
-- =========================================================

CREATE TABLE IF NOT EXISTS projects (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(100) NOT NULL,
    description     varchar(500),
    env             varchar(30) NOT NULL,
    owner_id        bigint NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_projects_owner
    FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT,

    CONSTRAINT chk_projects_env
    CHECK (env IN ('LOCAL', 'DEV', 'STAGE', 'PROD'))
    );

CREATE TABLE IF NOT EXISTS project_members (
        id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        project_id      bigint NOT NULL,
        user_id         bigint NOT NULL,
        member_role     varchar(50) NOT NULL,
        joined_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_project_members_project
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,

    CONSTRAINT fk_project_members_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT uq_project_members_project_user
    UNIQUE (project_id, user_id),

    CONSTRAINT chk_project_members_role
    CHECK (member_role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER'))
    );

CREATE TABLE IF NOT EXISTS services (
        id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        project_id      bigint NOT NULL,
        name            varchar(100) NOT NULL,
        service_key     varchar(100) NOT NULL UNIQUE,
        language        varchar(50),
        framework       varchar(100),
        status          varchar(30) NOT NULL DEFAULT 'ACTIVE',
        created_at      timestamptz NOT NULL DEFAULT now(),
        updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_services_project
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,

    CONSTRAINT uq_services_project_name
    UNIQUE (project_id, name),

    CONSTRAINT chk_services_status
    CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
    );

-- =========================================================
-- Log Source / Ingest
-- =========================================================

CREATE TABLE IF NOT EXISTS log_sources (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id      bigint NOT NULL,
    source_type     varchar(50) NOT NULL,
    source_name     varchar(100) NOT NULL,
    host_name       varchar(255),
    agent_version   varchar(50),
    status          varchar(30) NOT NULL DEFAULT 'ACTIVE',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_log_sources_service
    FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE,

    CONSTRAINT chk_log_sources_status
    CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED')),

    CONSTRAINT chk_log_sources_type
    CHECK (source_type IN ('AGENT', 'FILE', 'API', 'STDOUT', 'KAFKA'))
    );

CREATE TABLE IF NOT EXISTS log_ingest_batches (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_source_id   bigint NOT NULL,
    batch_key       varchar(150) NOT NULL UNIQUE,
    received_count  int NOT NULL DEFAULT 0,
    success_count   int NOT NULL DEFAULT 0,
    failed_count    int NOT NULL DEFAULT 0,
    status          varchar(30) NOT NULL DEFAULT 'STARTED',
    started_at      timestamptz NOT NULL DEFAULT now(),
    finished_at     timestamptz,

    CONSTRAINT fk_log_ingest_batches_log_source
    FOREIGN KEY (log_source_id) REFERENCES log_sources (id) ON DELETE CASCADE,

    CONSTRAINT chk_log_ingest_batches_status
    CHECK (status IN ('STARTED', 'COMPLETED', 'FAILED', 'PARTIAL_FAILED')),

    CONSTRAINT chk_log_ingest_batches_counts
    CHECK (received_count >= 0 AND success_count >= 0 AND failed_count >= 0)
    );

-- =========================================================
-- Log Event
-- =========================================================

CREATE TABLE IF NOT EXISTS log_events (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          bigint NOT NULL,
    service_id          bigint NOT NULL,
    log_source_id       bigint NOT NULL,
    ingest_batch_id     bigint,
    trace_id            varchar(128),
    span_id             varchar(128),
    level               varchar(20) NOT NULL,
    logger_name         varchar(255),
    message             varchar(4000) NOT NULL,
    error_type          varchar(255),
    environment         varchar(30),
    host_name           varchar(255),
    request_uri         varchar(1000),
    http_method         varchar(20),
    http_status         int,
    elapsed_ms          bigint,
    occurred_at         timestamptz NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_log_events_project
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,

    CONSTRAINT fk_log_events_service
    FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE,

    CONSTRAINT fk_log_events_log_source
    FOREIGN KEY (log_source_id) REFERENCES log_sources (id) ON DELETE CASCADE,

    CONSTRAINT fk_log_events_ingest_batch
    FOREIGN KEY (ingest_batch_id) REFERENCES log_ingest_batches (id) ON DELETE SET NULL,

    CONSTRAINT chk_log_events_level
    CHECK (level IN ('TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL')),

    CONSTRAINT chk_log_events_http_status
    CHECK (http_status IS NULL OR (http_status >= 100 AND http_status <= 599)),

    CONSTRAINT chk_log_events_elapsed_ms
    CHECK (elapsed_ms IS NULL OR elapsed_ms >= 0)
    );

CREATE TABLE IF NOT EXISTS log_event_raw (
     id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     log_event_id    bigint NOT NULL UNIQUE,
     raw_payload     jsonb,
     raw_message     text,
     created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_log_event_raw_log_event
    FOREIGN KEY (log_event_id) REFERENCES log_events (id) ON DELETE CASCADE
    );

-- =========================================================
-- Detection / Incident
-- =========================================================

CREATE TABLE IF NOT EXISTS detection_rules (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          bigint NOT NULL,
    name                varchar(150) NOT NULL,
    rule_type           varchar(50) NOT NULL,
    severity            varchar(20) NOT NULL,
    query_condition     text NOT NULL,
    threshold_count     int NOT NULL DEFAULT 1,
    window_minutes      int NOT NULL DEFAULT 5,
    enabled             boolean NOT NULL DEFAULT true,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_detection_rules_project
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,

    CONSTRAINT uq_detection_rules_project_name
    UNIQUE (project_id, name),

    CONSTRAINT chk_detection_rules_type
    CHECK (rule_type IN ('KEYWORD', 'LEVEL_THRESHOLD', 'HTTP_STATUS', 'ERROR_RATE', 'CUSTOM_QUERY')),

    CONSTRAINT chk_detection_rules_severity
    CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),

    CONSTRAINT chk_detection_rules_threshold
    CHECK (threshold_count > 0 AND window_minutes > 0)
    );

CREATE TABLE IF NOT EXISTS detected_incidents (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      bigint NOT NULL,
    service_id      bigint NOT NULL,
    rule_id         bigint NOT NULL,
    title           varchar(255) NOT NULL,
    severity        varchar(20) NOT NULL,
    status          varchar(30) NOT NULL DEFAULT 'OPEN',
    event_count     int NOT NULL DEFAULT 0,
    first_seen_at   timestamptz NOT NULL,
    last_seen_at    timestamptz NOT NULL,
    resolved_at     timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_detected_incidents_project
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,

    CONSTRAINT fk_detected_incidents_service
    FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE,

    CONSTRAINT fk_detected_incidents_rule
    FOREIGN KEY (rule_id) REFERENCES detection_rules (id) ON DELETE RESTRICT,

    CONSTRAINT chk_detected_incidents_severity
    CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),

    CONSTRAINT chk_detected_incidents_status
    CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'CLOSED')),

    CONSTRAINT chk_detected_incidents_event_count
    CHECK (event_count >= 0)
    );

CREATE TABLE IF NOT EXISTS incident_events (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id     bigint NOT NULL,
    log_event_id    bigint NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_incident_events_incident
    FOREIGN KEY (incident_id) REFERENCES detected_incidents (id) ON DELETE CASCADE,

    CONSTRAINT fk_incident_events_log_event
    FOREIGN KEY (log_event_id) REFERENCES log_events (id) ON DELETE CASCADE,

    CONSTRAINT uq_incident_events_incident_log_event
    UNIQUE (incident_id, log_event_id)
    );

-- =========================================================
-- Alert / Notification
-- =========================================================

CREATE TABLE IF NOT EXISTS alert_channels (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      bigint NOT NULL,
    channel_type    varchar(50) NOT NULL,
    name            varchar(100) NOT NULL,
    target_url      varchar(1000),
    target_email    varchar(255),
    enabled         boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_alert_channels_project
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,

    CONSTRAINT uq_alert_channels_project_name
    UNIQUE (project_id, name),

    CONSTRAINT chk_alert_channels_type
    CHECK (channel_type IN ('EMAIL', 'SLACK', 'WEBHOOK'))
    );

CREATE TABLE IF NOT EXISTS alert_notifications (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id          bigint NOT NULL,
    alert_channel_id     bigint NOT NULL,
    status              varchar(30) NOT NULL DEFAULT 'PENDING',
    retry_count         int NOT NULL DEFAULT 0,
    error_message       text,
    sent_at             timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_alert_notifications_incident
    FOREIGN KEY (incident_id) REFERENCES detected_incidents (id) ON DELETE CASCADE,

    CONSTRAINT fk_alert_notifications_channel
    FOREIGN KEY (alert_channel_id) REFERENCES alert_channels (id) ON DELETE CASCADE,

    CONSTRAINT chk_alert_notifications_status
    CHECK (status IN ('PENDING', 'SENT', 'FAILED')),

    CONSTRAINT chk_alert_notifications_retry_count
    CHECK (retry_count >= 0)
    );

-- =========================================================
-- Comment / Audit
-- =========================================================

CREATE TABLE IF NOT EXISTS incident_comments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id     bigint NOT NULL,
    user_id         bigint NOT NULL,
    comment         text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_incident_comments_incident
    FOREIGN KEY (incident_id) REFERENCES detected_incidents (id) ON DELETE CASCADE,

    CONSTRAINT fk_incident_comments_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS audit_logs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint,
    project_id      bigint,
    action_type     varchar(100) NOT NULL,
    target_type     varchar(100) NOT NULL,
    target_id       bigint,
    detail          jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_audit_logs_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT fk_audit_logs_project
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
    );

-- =========================================================
-- Indexes
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id
    ON user_roles (user_id);

CREATE INDEX IF NOT EXISTS idx_projects_owner_id
    ON projects (owner_id);

CREATE INDEX IF NOT EXISTS idx_project_members_project_id
    ON project_members (project_id);

CREATE INDEX IF NOT EXISTS idx_project_members_user_id
    ON project_members (user_id);

CREATE INDEX IF NOT EXISTS idx_services_project_id
    ON services (project_id);

CREATE INDEX IF NOT EXISTS idx_log_sources_service_id
    ON log_sources (service_id);

CREATE INDEX IF NOT EXISTS idx_log_ingest_batches_log_source_id
    ON log_ingest_batches (log_source_id);

CREATE INDEX IF NOT EXISTS idx_log_events_project_occurred_at
    ON log_events (project_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_log_events_service_occurred_at
    ON log_events (service_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_log_events_source_occurred_at
    ON log_events (log_source_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_log_events_batch_id
    ON log_events (ingest_batch_id);

CREATE INDEX IF NOT EXISTS idx_log_events_trace_id
    ON log_events (trace_id);

CREATE INDEX IF NOT EXISTS idx_log_events_level_occurred_at
    ON log_events (level, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_log_events_http_status_occurred_at
    ON log_events (http_status, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_log_events_message_trgm
    ON log_events USING gin (message gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_log_event_raw_payload_gin
    ON log_event_raw USING gin (raw_payload);

CREATE INDEX IF NOT EXISTS idx_detection_rules_project_id
    ON detection_rules (project_id);

CREATE INDEX IF NOT EXISTS idx_detected_incidents_project_status
    ON detected_incidents (project_id, status);

CREATE INDEX IF NOT EXISTS idx_detected_incidents_service_status
    ON detected_incidents (service_id, status);

CREATE INDEX IF NOT EXISTS idx_detected_incidents_rule_id
    ON detected_incidents (rule_id);

CREATE INDEX IF NOT EXISTS idx_incident_events_incident_id
    ON incident_events (incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_events_log_event_id
    ON incident_events (log_event_id);

CREATE INDEX IF NOT EXISTS idx_alert_channels_project_id
    ON alert_channels (project_id);

CREATE INDEX IF NOT EXISTS idx_alert_notifications_incident_id
    ON alert_notifications (incident_id);

CREATE INDEX IF NOT EXISTS idx_alert_notifications_channel_id
    ON alert_notifications (alert_channel_id);

CREATE INDEX IF NOT EXISTS idx_incident_comments_incident_id
    ON incident_comments (incident_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_created_at
    ON audit_logs (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_project_created_at
    ON audit_logs (project_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_target
    ON audit_logs (target_type, target_id);

-- =========================================================
-- Seed data for local development
-- =========================================================

INSERT INTO users (email, password_hash, display_name, status)
VALUES ('admin@example.com', '{noop}admin1234', 'Local Admin', 'ACTIVE')
    ON CONFLICT (email) DO NOTHING;

INSERT INTO user_roles (user_id, role)
SELECT id, 'ROLE_ADMIN'
FROM users
WHERE email = 'admin@example.com'
    ON CONFLICT (user_id, role) DO NOTHING;
